# Generated by Django 5.0.6 on 2024-05-24 08:08

import core.models
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='SRE0123456789', length=10, max_length=30, prefix='test', unique=True)),
                ('title', models.CharField(default='Title', max_length=100)),
                ('image', models.ImageField(default='image jpg ', upload_to=core.models.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='SRE0123456789', length=10, max_length=20, prefix='test', unique=True)),
                ('title', models.CharField(default='Title', max_length=100)),
                ('image', models.ImageField(default='image jpg ', upload_to=core.models.user_directory_path)),
                ('description', models.TextField(blank=True, default='Description', null=True)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=999999999)),
                ('specification', models.TextField(blank=True, default='Description', null=True)),
                ('product_status', models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled'), ('draft', 'draft'), ('rejected', 'Rejected')], default='in_review', max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=10, prefix='SKU-', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('upddated', models.DateTimeField(blank=True, null=True)),
                ('Category', models.ForeignKey(default='product category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='image.jpg', upload_to='product-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
