
# Generated by Django 5.0.4 on 2024-05-24 16:30

# Generated by Django 5.0.6 on 2024-05-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('disabled', 'Disabled'), ('draft', 'draft'), ('published', 'Published')], default='in_review', max_length=10),
        ),
    ]
