# Generated by Django 5.0.6 on 2024-05-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_product_status_alter_product_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('rejected', 'Rejected'), ('draft', 'draft'), ('published', 'Published')], default='in_review', max_length=10),
        ),
    ]
