# Generated by Django 5.0.4 on 2024-05-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_category_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('draft', 'draft'), ('rejected', 'Rejected'), ('published', 'Published')], default='in_review', max_length=10),
        ),
    ]
