# Generated by Django 5.0.4 on 2024-05-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
    ]
