# Generated by Django 5.0.4 on 2024-05-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_product_status_specialfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_features',
            field=models.TextField(blank=True, help_text='Enter special features separated by commas', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('draft', 'draft')], default='in_review', max_length=10),
        ),
        migrations.DeleteModel(
            name='SpecialFeature',
        ),
    ]
